spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://CHAITUNITHYA;databaseName=LibraryManagement;encrypt=true;trustServerCertificate=true;
    username: sa
    password: chaitu
  jpa:
    properties:
      hibernate:
        format_sql : true
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto : update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 465
    username: b21ai007@kitsw.ac.in
    password: flrj zsmi hcvo tnjg
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
server:
  port: 8095

